06 구현&코너케이스
Altu-Bitu-2/Algorithms_Altu-Bitu_Assignment pull request #4
Opened 2022-03-28 03:41 UTC by CSE-pebble

#### 내용 & 질문

> [1009] 예제출력도 정상적으로 되고 코너케이스도 모두 찾은 것 같은데 백준에서 자꾸 틀렸습니다가 나옵니다,, 어디에서 틀린 것일까요?

#### <기존 제출>

> 선택 : 1316

#### <추가 제출>

> 선택 :

2022-03-28 13:07 UTC, bsa0322 requested changes
p1. 과제 하시느라 수고하셨습니다!! 😊 함수화를 너무 깔끔하게 잘 해주셔서 보기 좋았어요~! 1009 관련 코멘트 남겼습니다. 1316은 조금 더 리팩토링할 수 있는 부분에 대해 남겼으니, 수정해보셔도 좋을 것 같아요! 수정하시거나 질문 있으시면 저 리뷰어로 호출해주세요~! 감사합니다 🥰

2022-03-28 13:07 UTC, bsa0322 commented on 03월 22일 - 구현 & 코너케이스/과제수행/1009.cpp
> +		temp *= a; // a 곱해주기
실수가 있네요! 일의 자리씩을 곱해주어야 하니 a가 아닌 무엇이 들어가야 할까요? 😉

2022-03-28 13:07 UTC, bsa0322 commented on 03월 22일 - 구현 & 코너케이스/과제수행/1009.cpp
> +		return 10; // 항상 10번째
a는 10보다 클 수도 있어요! 10일 때만 보는 것이 아니라 일의 자리로 접근해야 할 것 같아요! 🥰

2022-03-28 13:07 UTC, bsa0322 commented on 03월 22일 - 구현 & 코너케이스/과제수행/1316.cpp
> +	}
p1. 해당 변수를 함수 안에서 사용해주면 초기화 과정 없이 사용할 수 있어요 🥰

2022-03-28 13:07 UTC, bsa0322 commented on 03월 22일 - 구현 & 코너케이스/과제수행/1316.cpp
> +}
p2. 우선 함수화 너무 잘해주셨어요!! 해당 함수는 0과 1만 리턴하니 더 적합한 자료형이 있을 것 같네요! 🥰

더불어 16번째 줄에서 continue를 해주니 17 ~ 21줄의 인덴테이션을 줄일 수 있어 보여요! 

마지막으로 이건 사소한 건데, 지금 검사를 가장 많이 하는 인덱스가 i + 1이죠! 따라서 0부터가 아닌, 1부터 시작해주면 i로 바로 접근해서 조금 더 가독성 있는 코드를 만들 수 있어요! 😊

2022-03-28 15:45 UTC, bsa0322 commented
우선 선택 2문제 확인되셨습니다! 😊 내일까지 수정 후, 저 다시 리뷰어로 호출해주세요~!

2022-03-28 15:58 UTC, CSE-pebble commented
[11723] 백준 오류가 있는 것 같아서 맞은지는 정확히 모르겠는데 예제 출력은 정상적으로 나옵니다! 그런데 문자열의 경우 swith문을 쓸 수 없는 것이 맞나요? swith문이 훨씬 보기 좋을 것 같은데 쓰지 못하는 것 같아서요..!

2022-03-28 16:37 UTC, CSE-pebble commented
> p1. 과제 하시느라 수고하셨습니다!! 😊 함수화를 너무 깔끔하게 잘 해주셔서 보기 좋았어요~! 1009 관련 코멘트 남겼습니다. 1316은 조금 더 리팩토링할 수 있는 부분에 대해 남겼으니, 수정해보셔도 좋을 것 같아요! 수정하시거나 질문 있으시면 저 리뷰어로 호출해주세요~! 감사합니다 🥰

1009번 리뷰 남겨신 것 보고 수정했습니다! 그런데 계속 틀렸다고 나오네요.. 찾아봐도 잘 모르겠는데 어디가 문제일까요..?

2022-03-29 14:55 UTC, bsa0322 approved these changes
리뷰 늦어서 죄송합니다ㅜㅜ 우선 1009관련 코멘트 달았어요! 천천히 수정 후, 다시 리뷰어로 호출 부탁드립니다! :)

2022-03-30 09:14 UTC, bsa0322 approved these changes
리뷰 늦어서 죄송합니다 😭 1316과제 관련 추가 코멘트 달았습니다~! 
1009도 제가 위에 달은 코멘트 보고 수정하시면 금방 맞았습니다 뜨실 수 있을 거예요 ! 수정하시거나 질문 있으실 때 리뷰어로 호출 부탁드려요~! 감사합니다 🥰

2022-03-30 09:14 UTC, bsa0322 commented on 03월 22일 - 구현 & 코너케이스/과제수행/1316.cpp
> +}
좋아요~~!! 우선 p2 코멘트는 너무 잘 수정해주셨어요!! 🥰

p1에 대한 부분도 잘 접근해주셨는데요! 현재 check배열은 isGroup 함수에서만 사용되는데, main()에 선언해주어서 매번 isGroup의 매개로 넘겨주고 있어요! 보통 함수의 매개변수로 넘겨주는 경우는 메인에서 사용이 되던 변수가 해당 함수에도 필요할 때 넘겨주죠!
따라서 **isGroup 함수에만 사용되는 check 배열**을 지금보다 더 효율적으로 사용하려면 어떻게 해주면 될까요!!

2022-03-30 09:18 UTC, bsa0322 commented
> @bsa0322 [11723] vector만 사용했는데 왜 시간초과가 날까요? 그리고 문자열의 경우 swith문을 쓸 수 없는 것이 맞나요? swith문이 훨씬 보기 좋을 것 같은데 쓰지 못하는 것 같아서요..!

넵! c++에서는 switch-case 문의 조건으로 문자열을 쓸 수 없어요! 정수형태만 조건으로 가능해서, '문자'까지는 아스키코드로 변경 시 정수가 되기 때문에 사용이 가능합니다. 
더불어 11723 작성해주신 코드 확인했는데, 벡터를 사용해주셨지만, empty()체크 및 push_back() 형태로 계속 연산이 일어나기 때문에 시간초과가 나고 있어요! 해당 함수들 모두 시간복잡도가 O(1)이긴 하지만 해당 문제는 시간에 아주 예민하기 때문에 인덱스로 접근해서 값을 관리하는 것 말고는 시간초과가 납니다! 그룹 단어 체커 문제에서 사용한 check배열 느낌으로 11723의 집합을 관리해볼까요!

2022-03-31 08:56 UTC, CSE-pebble commented
> > @bsa0322 [11723] vector만 사용했는데 왜 시간초과가 날까요? 그리고 문자열의 경우 swith문을 쓸 수 없는 것이 맞나요? swith문이 훨씬 보기 좋을 것 같은데 쓰지 못하는 것 같아서요..!
> 
> 넵! c++에서는 switch-case 문의 조건으로 문자열을 쓸 수 없어요! 정수형태만 조건으로 가능해서, '문자'까지는 아스키코드로 변경 시 정수가 되기 때문에 사용이 가능합니다. 더불어 11723 작성해주신 코드 확인했는데, 벡터를 사용해주셨지만, empty()체크 및 push_back() 형태로 계속 연산이 일어나기 때문에 시간초과가 나고 있어요! 해당 함수들 모두 시간복잡도가 O(1)이긴 하지만 해당 문제는 시간에 아주 예민하기 때문에 인덱스로 접근해서 값을 관리하는 것 말고는 시간초과가 납니다! 그룹 단어 체커 문제에서 사용한 check배열 느낌으로 11723의 집합을 관리해볼까요!

이해됐어요! 답변 정말 감사합니다 ❤️ 제 코드에서 맞으려면 거의 전부를 다 수정해야할 것 같아서,, 따로 수정은 안하고 올려주신 샘플코드로 열심히 공부하겠습니다!!

그런데 저 문제에서 시간이 중요하다는 것을 어떻게 알 수 있나요? 제 코드가 시간복잡도도 큰 편이 아니어서 코드를 돌리고 시간초과라고 뜨기 전까지는 시간이 넘을거라는 생각은 전혀 못했거든요..! 😢  이런 유형은 처음부터 맞는 것은 거의 불가능하다고 보면 될까요..?

2022-03-31 09:00 UTC, CSE-pebble commented
> 리뷰 늦어서 죄송합니다 😭 1316과제 관련 추가 코멘트 달았습니다~! 1009도 제가 위에 달은 코멘트 보고 수정하시면 금방 맞았습니다 뜨실 수 있을 거예요 ! 수정하시거나 질문 있으실 때 리뷰어로 호출 부탁드려요~! 감사합니다 🥰

1009, 1316 모두 수정했습니다!! 확인 부탁드려요! 감사합니다 🥰

2022-04-01 16:20 UTC, bsa0322 commented
> > > @bsa0322 [11723] vector만 사용했는데 왜 시간초과가 날까요? 그리고 문자열의 경우 swith문을 쓸 수 없는 것이 맞나요? swith문이 훨씬 보기 좋을 것 같은데 쓰지 못하는 것 같아서요..!
> > 
> > 
> > 넵! c++에서는 switch-case 문의 조건으로 문자열을 쓸 수 없어요! 정수형태만 조건으로 가능해서, '문자'까지는 아스키코드로 변경 시 정수가 되기 때문에 사용이 가능합니다. 더불어 11723 작성해주신 코드 확인했는데, 벡터를 사용해주셨지만, empty()체크 및 push_back() 형태로 계속 연산이 일어나기 때문에 시간초과가 나고 있어요! 해당 함수들 모두 시간복잡도가 O(1)이긴 하지만 해당 문제는 시간에 아주 예민하기 때문에 인덱스로 접근해서 값을 관리하는 것 말고는 시간초과가 납니다! 그룹 단어 체커 문제에서 사용한 check배열 느낌으로 11723의 집합을 관리해볼까요!
> 
> 이해됐어요! 답변 정말 감사합니다 ❤️ 제 코드에서 맞으려면 거의 전부를 다 수정해야할 것 같아서,, 따로 수정은 안하고 올려주신 샘플코드로 열심히 공부하겠습니다!!
> 
> 그런데 저 문제에서 시간이 중요하다는 것을 어떻게 알 수 있나요? 제 코드가 시간복잡도도 큰 편이 아니어서 백준에 코드 돌리고 시간초과라고 뜨기 전까지는 시간이 넘을거라는 생각은 전혀 못했거든요..! 😢 이런 유형은 처음부터 맞는 것은 거의 불가능하다고 보면 될까요..?

헉 나현님..! 정말 죄송합니다 😭 제가 코멘트를 잘못 드렸어요. 더 확실히 확인하고 드렸어야 하는건데..!!! **나현님 현재 코드에서 시간초과가 나는 부분은 empty()와 push_back() 사용 때문이 아니였습니다.** 나현님 말씀대로 코드 자체의 시간복잡도는 큰 편이 아니에요! cin, cout의 속도가 느려서 난 문제였는데요. 아마 입출력속도 향상 코드만 추가해주시면 바로 맞았습니다 뜨는 거 보실 수 있을 거예요 😊 잘못 코멘트 드린 점 정말 죄송합니다 ㅠㅠㅠㅠ empty() 와 push_back() 모두 시간복잡도가 O(1) 이여서 웬만한 문제에선 괜찮을거예요!!!!

cin, cout 속도 관련해선 이렇게 입출력이 많은 문제에선 주로 사용해주시면 될 것 같습니다! 감사합니다. 🥰

2022-04-01 16:27 UTC, bsa0322 approved these changes
수정해주신 부분 모두 확인했습니다! 제가 말씀드린 부분을 너무 잘 캐치해주셨네요!! 👍 선택 2문제와 추가제출 1문제로 체크하도록 할께요. 머지해주셔도 괜찮습니다. 감사합니다~! 😍

2022-04-01 16:27 UTC, bsa0322 commented on 03월 22일 - 구현 & 코너케이스/과제수행/1009.cpp
> +		a_pow += cnt; // 0이 된 a_pow에 패턴 횟수만큼을 더해서 패턴 중 마지막 숫자로 가도록 하기
👍👍👍

2022-04-01 16:27 UTC, bsa0322 commented on 03월 22일 - 구현 & 코너케이스/과제수행/1316.cpp
> +	vector<int> check(26, 0); // 해당 알파벳이 문자열에서 등장했는지 확인해주는 vector
좋아요~~!!

2022-04-03 13:05 UTC, CSE-pebble commented
@bsa0322 튜터님 덕분에 제출한 문제 다 수정했습니다!! 감사합니다 ❤️

2022-04-03 17:06 UTC, closed without merging